- name: install epel-release
  yum: name={{ item }} state=latest
  with_items:
    - epel-release
  tags: setup

- name: epel.repo check baseful
  replace: >-
    dest='/etc/yum.repos.d/epel.repo'
    regexp='#baseurl='
    replace='baseurl='

- name: epel.repo check mirrorlist
  replace: >-
    dest='/etc/yum.repos.d/epel.repo'
    regexp='mirrorlist='
    replace='#mirrorlist='

- name: check whether nodejs exist or not
  stat: path="{{ nodejs_download_path }}/{{ nodejs_path }}"
  register: exists_nodejs
  tags: setup

- name: download node.js
  get_url: url="{{ nodejs_url }}"  sha256sum="{{ sha256sum_num2 }}" dest="{{ nodejs_download_path }}" force=True
  tags: setup

- name: unarchive node.js.tar.gz
  unarchive: src="{{ nodejs_download_path }}/{{ nodejs_path }}" dest=/usr/local copy=no
  when: exists_nodejs.stat.md5 is not defined
  tags: setup
